### ISSUE TITLE
Please update svgbob to latest version

### ISSUE THREAD

**Issue by dmayle** [agoose77/svgbob-wasm#1]
While 0.5.0 hasn't been released yet, svgbob seems pretty stable and I'd love to get access to styling.

**Comment by agoose77** [comment]
Okay, I'll take a look soon, we could make a prerelease. I'd welcome a PR as right now work is very busy!

**Comment by fabiospampinato** [comment]
It'd be nice if the build got updated to latest, a decent number of bugs seems to have been fixed compared to the version compiled here.

**Comment by agoose77** [comment]
I forgot about this issue - I've released a 1.0 version that uses the latest svgbob!

**Comment by fabiospampinato** [comment]
Awesome! Thank you so much!
