### ISSUE TITLE
ERROR in ./node_modules/svgbob-wasm/svgbob_wasm_bg.wasm 1:0

### ISSUE THREAD

**Issue by forwhat461** [agoose77/svgbob-wasm#15]
when i build it..

Module parse failed: Unexpected character '' (1:0)
The module seem to be a WebAssembly module, but module is not flagged as WebAssembly module for webpack.

BREAKING CHANGE: Since webpack 5 WebAssembly is not enabled by default and flagged as experimental feature.

**Comment by agoose77** [comment]
It took me a second to figure out what you were doing to get this error. I realised that you're trying out the demo?

I've updated the demo to use webpack 5, and cleaned up the README. Try pulling from `master` and follow the new README

**Comment by forwhat461** [comment]
windows10 > npm i [-g] wasm-pack
npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.
npm ERR! code 1
npm ERR! path C:\Users\lenovo\AppData\Roaming\npm\node_modules\wasm-pack
npm ERR! command failed
npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c node ./install.js
npm ERR! Downloading release from https://github.com/rustwasm/wasm-pack/releases/download/v0.10.3/wasm-pack-v0.10.3-x86_64-pc-windows-msvc.tar.gz
npm ERR! Error fetching release: unable to verify the first certificate

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\lenovo\AppData\Local\npm-cache\_logs\2022-09-09T08_28_02_700Z-debug-0.log

已经关闭了ssl验证
SSL authentication has been disabled
> npm config get strict-ssl  
> false  
虽然这次是wasm-pack的问题了。。
This time, though, it's the wasm-pack ？
